/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ajaj895.synblocks.gui;

import com.ajaj895.synblocks.core.blocks.Block; 
import com.ajaj895.synblocks.core.FileHandler;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.TransferHandler;

/**
 *
 * @author Evan
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    
    String code = "";
    int selLang = 0;//0 = Java, 1 = Python
    FileHandler fh = new FileHandler();
    
    public Gui() {
        initComponents();
        
        setTitle("Syn-Blocks | Syntax Learning Tool");//Window title
        
        //Block testBlock = new Block(curlyBracLabel.getText(), curlyBracLabel, 0, curlyBracLabel.getX(), curlyBracLabel.getX(), curlyBracLabel.getY(), curlyBracLabel.getY());//TESTING
        
        //classNameField.setDragEnabled(true);//Sets drag and drop
        //curlyBracLabel.setTransferHandler(new TransferHandler("text"));// I am citing this website for inspiring me with this solution http://zetcode.com/tutorials/javaswingtutorial/draganddrop/ for the drag and drop technique.
        publicClass.setDragEnabled(true);
        
        // ### DRAG ENABLE LOGIC FOR ALL TABS OF THE TABBED PANE ###
        for( Component com : baseTab.getComponents()){//Goes through each tab of the tabbed pane
            if(com.getClass().equals(basicTab.getClass())){//Tests for JPanel Class 
                JPanel temp = (JPanel)com;
                for( Component txtFields : temp.getComponents()){
                    if(txtFields.getClass().equals(classNameField.getClass())){
                        JTextField txtTemp = (JTextField)txtFields;
                        txtTemp.setDragEnabled(true);
                    }
                }
            }
        }
        
        // ### DROP ENABLE LOGIC FOR THE CODING PANEL ###
        for( Component com : codingPanel.getComponents()){//For the coding panel
            if(com.getClass().equals(label8.getClass())){//Tests for JLabel class
                JLabel temp = (JLabel)com;
                temp.setTransferHandler(new TransferHandler("text")); 
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workFrame = new javax.swing.JScrollPane();
        codingPanel = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label16 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label17 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        langList = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        baseTab = new javax.swing.JTabbedPane();
        basicTab = new javax.swing.JPanel();
        classNameField = new javax.swing.JTextField();
        pubStatVoidMain = new javax.swing.JTextField();
        publicClass = new javax.swing.JTextField();
        stringArgs = new javax.swing.JTextField();
        openCurly = new javax.swing.JTextField();
        closeCurly = new javax.swing.JTextField();
        systemLabel = new javax.swing.JTextField();
        outLabel = new javax.swing.JTextField();
        printLabel = new javax.swing.JTextField();
        openParenth = new javax.swing.JTextField();
        closeParenth = new javax.swing.JTextField();
        semicolon = new javax.swing.JTextField();
        semicolon1 = new javax.swing.JTextField();
        loopTab = new javax.swing.JPanel();
        logicTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveButton = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        runButton = new javax.swing.JMenuItem();
        compileButton = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label8.setToolTipText("Curly braces. The most common form of syntax in Java, used after loops, methods, and class statements.");
        label8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label4.setText(" ");
        label4.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label6.setToolTipText("Curly braces. The most common form of syntax in Java, used after loops, methods, and class statements.");
        label6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label7.setText(" ");
        label7.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label9.setToolTipText("Curly braces. The most common form of syntax in Java, used after loops, methods, and class statements.");
        label9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label10.setText(" ");
        label10.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label16.setToolTipText("Curly braces. The most common form of syntax in Java, used after loops, methods, and class statements.");
        label16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label3.setToolTipText("Curly braces. The most common form of syntax in Java, used after loops, methods, and class statements.");
        label3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label12.setToolTipText("Curly braces. The most common form of syntax in Java, used after loops, methods, and class statements.");
        label12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label13.setText(" ");
        label13.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label1.setText(" ");
        label1.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label15.setText(" ");
        label15.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label2.setText(" ");
        label2.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label14.setToolTipText("Curly braces. The most common form of syntax in Java, used after loops, methods, and class statements.");
        label14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label17.setText(" ");
        label17.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label5.setText(" ");
        label5.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label11.setText(" ");
        label11.setToolTipText("Public class [name]. This is the base of all Java files, where Public makes it accessable, Class declares that it is a Java file, and the text box is a name of your choice.");
        label11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout codingPanelLayout = new javax.swing.GroupLayout(codingPanel);
        codingPanel.setLayout(codingPanelLayout);
        codingPanelLayout.setHorizontalGroup(
            codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codingPanelLayout.createSequentialGroup()
                .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(codingPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(codingPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(codingPanelLayout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(codingPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(codingPanelLayout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        codingPanelLayout.setVerticalGroup(
            codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label1)
                        .addComponent(label2))
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label4)
                        .addComponent(label5))
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label15, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label13, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(codingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label10)
                        .addComponent(label11))
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label17)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        workFrame.setViewportView(codingPanel);

        jLabel1.setText("Syn-Blocks");

        jLabel2.setText("A syntax learning tool.");

        langList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "Python" }));
        langList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langListActionPerformed(evt);
            }
        });

        jLabel3.setText("Language");

        baseTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        baseTab.setRequestFocusEnabled(false);

        classNameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        classNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classNameFieldActionPerformed(evt);
            }
        });

        pubStatVoidMain.setEditable(false);
        pubStatVoidMain.setText("public static void main");
        pubStatVoidMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        publicClass.setEditable(false);
        publicClass.setText("public class ");
        publicClass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        stringArgs.setEditable(false);
        stringArgs.setText("(String[] args)");
        stringArgs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        openCurly.setEditable(false);
        openCurly.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        openCurly.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        openCurly.setText("{");
        openCurly.setToolTipText("Open curly brace. DON'T FORGET TO CLOSE THE BRACE BY GIVING THIS BRACE A FRIEND :)");
        openCurly.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openCurly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCurlyActionPerformed(evt);
            }
        });

        closeCurly.setEditable(false);
        closeCurly.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeCurly.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        closeCurly.setText("}");
        closeCurly.setToolTipText("Closing curly brace. A useful friend for the open curly brace and necessary to close a section of code.");
        closeCurly.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeCurly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCurlyActionPerformed(evt);
            }
        });

        systemLabel.setEditable(false);
        systemLabel.setText("System");
        systemLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        outLabel.setEditable(false);
        outLabel.setText("out");
        outLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        outLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outLabelActionPerformed(evt);
            }
        });

        printLabel.setEditable(false);
        printLabel.setText("print");
        printLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        openParenth.setEditable(false);
        openParenth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        openParenth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        openParenth.setText("(");
        openParenth.setToolTipText("Open curly brace. DON'T FORGET TO CLOSE THE BRACE BY GIVING THIS BRACE A FRIEND :)");
        openParenth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openParenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openParenthActionPerformed(evt);
            }
        });

        closeParenth.setEditable(false);
        closeParenth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeParenth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        closeParenth.setText(")");
        closeParenth.setToolTipText("Open curly brace. DON'T FORGET TO CLOSE THE BRACE BY GIVING THIS BRACE A FRIEND :)");
        closeParenth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeParenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeParenthActionPerformed(evt);
            }
        });

        semicolon.setEditable(false);
        semicolon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        semicolon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semicolon.setText(";");
        semicolon.setToolTipText("Open curly brace. DON'T FORGET TO CLOSE THE BRACE BY GIVING THIS BRACE A FRIEND :)");
        semicolon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        semicolon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semicolonActionPerformed(evt);
            }
        });

        semicolon1.setEditable(false);
        semicolon1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        semicolon1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semicolon1.setText(".");
        semicolon1.setToolTipText("Open curly brace. DON'T FORGET TO CLOSE THE BRACE BY GIVING THIS BRACE A FRIEND :)");
        semicolon1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        semicolon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semicolon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basicTabLayout = new javax.swing.GroupLayout(basicTab);
        basicTab.setLayout(basicTabLayout);
        basicTabLayout.setHorizontalGroup(
            basicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, basicTabLayout.createSequentialGroup()
                            .addComponent(publicClass, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(classNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, basicTabLayout.createSequentialGroup()
                            .addComponent(openCurly, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(closeCurly, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(openParenth, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(closeParenth, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(semicolon1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(semicolon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(stringArgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pubStatVoidMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basicTabLayout.createSequentialGroup()
                        .addComponent(systemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        basicTabLayout.setVerticalGroup(
            basicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicTabLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(basicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openCurly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeCurly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openParenth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeParenth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semicolon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semicolon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publicClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pubStatVoidMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stringArgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        baseTab.addTab("Basics", basicTab);

        javax.swing.GroupLayout loopTabLayout = new javax.swing.GroupLayout(loopTab);
        loopTab.setLayout(loopTabLayout);
        loopTabLayout.setHorizontalGroup(
            loopTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        loopTabLayout.setVerticalGroup(
            loopTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        baseTab.addTab("Loops", loopTab);

        javax.swing.GroupLayout logicTabLayout = new javax.swing.GroupLayout(logicTab);
        logicTab.setLayout(logicTabLayout);
        logicTabLayout.setHorizontalGroup(
            logicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        logicTabLayout.setVerticalGroup(
            logicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        baseTab.addTab("Logic", logicTab);

        baseTab.setSelectedComponent(basicTab);

        jLabel4.setText("Blocks");

        fileMenu.setText("File");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        fileMenu.add(saveButton);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");
        jMenuBar1.add(editMenu);

        jMenu3.setText("Run");

        runButton.setText("Run");
        jMenu3.add(runButton);

        compileButton.setText("Compile");
        jMenu3.add(compileButton);

        jMenuBar1.add(jMenu3);

        optionsMenu.setText("Options");
        jMenuBar1.add(optionsMenu);

        jMenu1.setText("Help");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baseTab)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(251, 251, 251))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(217, 217, 217)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(langList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(workFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(langList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baseTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(workFrame))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classNameFieldActionPerformed

    private void closeCurlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCurlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeCurlyActionPerformed

    private void openCurlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCurlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openCurlyActionPerformed

    private void outLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outLabelActionPerformed

    private void openParenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openParenthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openParenthActionPerformed

    private void closeParenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeParenthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeParenthActionPerformed

    private void semicolonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semicolonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semicolonActionPerformed

    private void semicolon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semicolon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semicolon1ActionPerformed

    private void langListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langListActionPerformed
        // TODO add your handling code here:
        selLang = langList.getSelectedIndex();
        //System.out.println(selLang);//for testing purposes.
    }//GEN-LAST:event_langListActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        //Similar logic loop as before but this time to get text from the JLabels
        int tabage = 0;//Number of tabs
        //TODO Make this better, this is a bandaid over a bullet hole solution.
        code += label1.getText();
        if(label1.getText().equalsIgnoreCase(";") || label1.getText().equalsIgnoreCase("}")) code += "\n"; 
        if(label1.getText().equalsIgnoreCase("{")) code += "\n";
        code += label2.getText();
        if(label2.getText().equalsIgnoreCase(";") || label2.getText().equalsIgnoreCase("}")) code += "\n"; 
        if(label2.getText().equalsIgnoreCase("{")) code += "\n";
        code += label3.getText();
        if(label3.getText().equalsIgnoreCase(";") || label3.getText().equalsIgnoreCase("}")) code += "\n";
        if(label3.getText().equalsIgnoreCase("{")) code += "\n";
        code += label4.getText();
        if(label4.getText().equalsIgnoreCase(";") || label4.getText().equalsIgnoreCase("}")) code += "\n"; 
        if(label4.getText().equalsIgnoreCase("{")) code += "\n";
        code += label5.getText();
        if(label5.getText().equalsIgnoreCase(";") || label5.getText().equalsIgnoreCase("}")) code += "\n";
        if(label5.getText().equalsIgnoreCase("{")) code += "\n";
        code += label6.getText();
        if(label6.getText().equalsIgnoreCase(";") || label6.getText().equalsIgnoreCase("}")) code += "\n";
        if(label6.getText().equalsIgnoreCase("{")) code += "\n";
        code += label7.getText();
        if(label7.getText().equalsIgnoreCase(";") || label7.getText().equalsIgnoreCase("}")) code += "\n";
        if(label7.getText().equalsIgnoreCase("{")) code += "\n";
        code += label8.getText();
        if(label8.getText().equalsIgnoreCase(";") || label8.getText().equalsIgnoreCase("}")) code += "\n";
        if(label8.getText().equalsIgnoreCase("{")) code += "\n";
        code += label9.getText();
        if(label9.getText().equalsIgnoreCase(";") || label9.getText().equalsIgnoreCase("}")) code += "\n";
        if(label9.getText().equalsIgnoreCase("{")) code += "\n";
        code += label10.getText();
        if(label10.getText().equalsIgnoreCase(";") || label10.getText().equalsIgnoreCase("}")) code += "\n";
        if(label10.getText().equalsIgnoreCase("{")) code += "\n";
        code += label11.getText();
        if(label11.getText().equalsIgnoreCase(";") || label11.getText().equalsIgnoreCase("}")) code += "\n";
        if(label11.getText().equalsIgnoreCase("{")) code += "\n";
        code += label12.getText();
        if(label12.getText().equalsIgnoreCase(";") || label12.getText().equalsIgnoreCase("}")) code += "\n"; 
        if(label12.getText().equalsIgnoreCase("{")) code += "\n";
        code += label13.getText();
        if(label13.getText().equalsIgnoreCase(";") || label13.getText().equalsIgnoreCase("}")) code += "\n";
        if(label13.getText().equalsIgnoreCase("{")) code += "\n";
        code += label14.getText();
        if(label14.getText().equalsIgnoreCase(";") || label14.getText().equalsIgnoreCase("}")) code += "\n";
        if(label14.getText().equalsIgnoreCase("{")) code += "\n";
        code += label15.getText();
        if(label15.getText().equalsIgnoreCase(";") || label15.getText().equalsIgnoreCase("}")) code += "\n";
        if(label15.getText().equalsIgnoreCase("{")) code += "\n";
        code += label16.getText();
        if(label16.getText().equalsIgnoreCase(";") || label16.getText().equalsIgnoreCase("}")) code += "\n";
        if(label6.getText().equalsIgnoreCase("{")) code += "\n";
        code += label17.getText();
        if(label17.getText().equalsIgnoreCase(";") || label17.getText().equalsIgnoreCase("}")) code += "\n";
        if(label17.getText().equalsIgnoreCase("{")) code += "\n";
        
        System.out.println(code);//for Testing purposes.
        
        fh.saveFile(label2.getText()+".java", code);
        code = "";//Reseting memory so no double saving of the same data.
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane baseTab;
    private javax.swing.JPanel basicTab;
    private javax.swing.JTextField classNameField;
    private javax.swing.JTextField closeCurly;
    private javax.swing.JTextField closeParenth;
    private javax.swing.JPanel codingPanel;
    private javax.swing.JMenuItem compileButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JComboBox<String> langList;
    private javax.swing.JPanel logicTab;
    private javax.swing.JPanel loopTab;
    private javax.swing.JTextField openCurly;
    private javax.swing.JTextField openParenth;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JTextField outLabel;
    private javax.swing.JTextField printLabel;
    private javax.swing.JTextField pubStatVoidMain;
    private javax.swing.JTextField publicClass;
    private javax.swing.JMenuItem runButton;
    private javax.swing.JMenuItem saveButton;
    private javax.swing.JTextField semicolon;
    private javax.swing.JTextField semicolon1;
    private javax.swing.JTextField stringArgs;
    private javax.swing.JTextField systemLabel;
    private javax.swing.JScrollPane workFrame;
    // End of variables declaration//GEN-END:variables


    
}
